version: '3'

services:
  order-postgres:
    container_name: order-postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: order-service
      POSTGRES_USER: java
      POSTGRES_PASSWORD: spring
      PGDATA: /data/postgres
    volumes:
      - ./order-postgres:/data/postgres
    expose:
      - "54321"
    ports:
      - "54321:5432"
    command: -p 54321
    restart: unless-stopped

  inventory-postgres:
    container_name: inventory-postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: inventory-service
      POSTGRES_USER: java
      POSTGRES_PASSWORD: spring
      PGDATA: /data/postgres
    volumes:
      - ./inventory-postgres:/data/postgres
    expose:
      - "54322"
    ports:
      - "54322:5432"
    command: -p 54322
    restart: unless-stopped

  product-mongo:
    container_name: product-mongo
    image: mongo:latest
    volumes:
      - ./mongo-data:/data/db
    expose:
      - "27017"
    ports:
      - "27017:27017"
    restart: unless-stopped

  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: java
      MYSQL_PASSWORD: spring
    volumes:
      - ./keycloak-mysql-data:/var/lib/mysql

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:23.0.7
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: java
      DB_PASSWORD: spring
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./realms/:/opt/keycloak/data/import
    command: ["start-dev", "--import-realm"]
    depends_on:
      - keycloak-mysql

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka-broker-1:
    container_name: kafka-broker-1
    image: confluentinc/cp-kafka:latest
    hostname: kafka-broker-1
    ports:
      - "19092:19092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-1:9092,PLAINTEXT_INTERNAL://localhost:19092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  discovery-server:
    container_name: discovery-server
    image: zangura77/discovery-server:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8761:8761"
    depends_on:
      - zipkin

  api-gateway:
    container_name: api-gateway
    image: zangura77/api-gateway:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=TRACE
    ports:
      - "8181:8080"
    expose:
      - "8181"
    depends_on:
      - zipkin
      - discovery-server
      - keycloak

  product-service:
    container_name: product-service
    image: zangura77/product-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - product-mongo
      - discovery-server
      - api-gateway

  order-service:
    container_name: order-service
    image: zangura77/order-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc://order-postgres:54321/order-service
    depends_on:
      - order-postgres
      - kafka-broker-1
      - zipkin
      - discovery-server
      - api-gateway

  inventory-service:
    container_name: inventory-service
    image: zangura77/inventory-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc://inventory-postgres:54322/inventory-service
    depends_on:
      - inventory-postgres
      - discovery-server
      - api-gateway

  notification-service:
    container_name: notification-service
    image: zangura77/notification-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin
      - kafka-broker-1
      - discovery-server
      - api-gateway