spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:54322/inventory-service
    username: java
    password: spring
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: service
    hibernate:
      ddl-auto: none

  ## Zipkin and Sleuth properties
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka